Repository Happy-New-Here/HappyNewHere_FE, pull requests merged in 2023-12, with the labels that each got.

#23 Feat/issue-#20
  src/App.jsx
  src/assets/envelopeIconRed.svg
  src/assets/envelopeIconWhite.svg
  src/components/common/MessageWriteButton.jsx
  src/components/organisms/Message/MessageWriteButtonOrganism.jsx
  src/components/template/FriendTemplate.jsx
  src/components/template/MessageWriteTemplate.jsx
  src/pages/Friend.jsx
  src/pages/MessageWrite.jsx
  src/store/isMessageWriteVisibleSlice.js
  src/store/store.js
  src/styles/utils.jsx
Labels: ✨ Feature, 🔨 Refactor

#25 Feat/issue-#24
  src/App.jsx
  src/assets/logo.svg
  src/assets/logoDarkmode.svg
  src/components/common/Header.jsx
  src/components/common/Logo.jsx
  src/components/template/FriendTemplate.jsx
  src/pages/Root.jsx
  src/styles/utils.jsx
Labels: ✨ Feature, 🎨 Styling

#26 Feat/issue-#8
  package-lock.json
  package.json
  postcss.config.js
  src/App.css
  src/App.jsx
  src/assets/logo.png
  src/components/template/IdTemplate.jsx
  src/components/template/NicknameTemplate.jsx
  src/index.css
  src/pages/IdInput.jsx
  src/pages/Nickname.jsx
  tailwind.config.js
  yarn.lock
Labels: ✨ Feature, 🌇 Establish, 📬 API

#35 Feat/issue-#2
  package-lock.json
  src/App.jsx
  src/components/common/Button/KakaoLoginBtn.jsx
  src/components/common/KakaoLoginBtn.css
  src/components/common/KakaoLoginBtn.jsx
  src/components/template/AuthRedirect.jsx
  src/components/template/AuthRedirectTemplate.jsx
  src/components/template/AuthTemplate.jsx
  src/pages/Auth.jsx
  src/pages/AuthRedirectPage.jsx
  src/styles/color.scss
  src/styles/font.scss
  src/styles/utils.scss
  src/utils/URL.jsx
  yarn.lock
Labels: ✨ Feature, 🎨 Styling, ✅ Test

#36 Feat/issue-#3
  .eslintrc.cjs
  .gitignore
  package-lock.json
  package.json
  postcss.config.js
  src/App.css
  src/components/common/MessageSendButton.jsx
  src/components/common/Search/SearchBar.jsx
  src/components/organisms/Search/RecentSearch.jsx
  src/components/organisms/Search/ResultSearch.jsx
  src/components/organisms/Search/SearchBar.jsx
  src/components/template/SearchTemplate.jsx
  src/index.css
  src/main.jsx
  src/store/search-action.js
  src/store/searchSlice.js
  src/store/store.js
  src/styles/text.jsx
  src/styles/utils.jsx
  tailwind.config.js
  vite.config.js
Labels: ✨ Feature, 🎨 Styling, ✅ Test

#38 Feat/issue-#37
  package-lock.json
  package.json
  src/App.jsx
  src/assets/AuthPageDeco.svg
  src/assets/HappyHaedalLogo.svg
  src/assets/SnowMan.svg
  src/components/template/AuthTemplate.jsx
  src/styles/text.jsx
Labels: ✨ Feature, 🎨 Styling

#47 Fix/issue-#46
  src/App.jsx
Labels: 👹 Bug, 📬 API

#48 Feat/issue-#22
  src/assets/editIcon.svg
  src/components/common/Profile.jsx
  src/components/template/FriendTemplate.jsx
Labels: ✨ Feature, ✅ Test

#45 Feat/issue-#5
  package-lock.json
  package.json
  src/assets/bell_green.svg
  src/assets/bell_maroon.svg
  src/assets/bell_navy.svg
  src/assets/bell_pink.svg
  src/assets/bell_red.svg
  src/assets/bell_white.svg
  src/assets/bell_yellow.svg
  src/components/common/BellSVG.jsx
  src/components/common/Calendar.jsx
  src/components/common/GiftBox.jsx
  src/components/template/AuthRedirectTemplate.jsx
  src/components/template/AuthTemplate.jsx
  src/components/template/HomeTemplate.jsx
  tailwind.config.js
Labels: ✨ Feature, 🎨 Styling, ✅ Test

#52 Feat/issue-#50
  src/assets/MessagePaper1.png
  src/assets/MessagePaper2.png
  src/assets/MessagePaper3.png
  src/assets/MessagePapers/Brown/Puppy.svg
  src/assets/MessagePapers/Brown/Santa.svg
  src/assets/MessagePapers/Brown/Snowman.svg
  src/assets/MessagePapers/Brown/Town.svg
  src/assets/MessagePapers/Green/Puppy.svg
  src/assets/MessagePapers/Green/Santa.svg
  src/assets/MessagePapers/Green/Snowman.svg
  src/assets/MessagePapers/Green/Town.svg
  src/assets/MessagePapers/Navy/Puppy.svg
  src/assets/MessagePapers/Navy/Santa.svg
  src/assets/MessagePapers/Navy/Snowman.svg
  src/assets/MessagePapers/Navy/Town.svg
  src/assets/MessagePapers/Pink/Puppy.svg
  src/assets/MessagePapers/Pink/Santa.svg
  src/assets/MessagePapers/Pink/Snowman.svg
  src/assets/MessagePapers/Pink/Town.svg
  src/assets/MessagePapers/Red/Puppy.svg
  src/assets/MessagePapers/Red/Santa.svg
  src/assets/MessagePapers/Red/Snowman.svg
  src/assets/MessagePapers/Red/Town.svg
  src/assets/MessagePapers/White/Puppy.svg
  src/assets/MessagePapers/White/Santa.svg
  src/assets/MessagePapers/White/Snowman.svg
  src/assets/MessagePapers/White/Town.svg
  src/assets/MessagePapers/Yellow/Puppy.svg
  src/assets/MessagePapers/Yellow/Santa.svg
  src/assets/MessagePapers/Yellow/Snowman.svg
  src/assets/MessagePapers/Yellow/Town.svg
  src/components/common/MessagePaperThumbnail.jsx
  src/components/common/MessageSendButton.jsx
  src/components/common/MessageThumbnail.jsx
  src/components/common/MessageView.jsx
  src/components/common/MessageWrite.jsx
  src/components/common/Profile.jsx
  src/components/organisms/Message/MessagePaperThumbnailOrganism.jsx
  src/store/selectedPaperNumSlice.js
  src/styles/messageStyles.jsx
  src/utils/MessagePapersSRC.jsx
  src/utils/messagePaperSRC.jsx
  vite.config.js
Labels: ✨ Feature, 🎨 Styling

#54 Style/issue-#53
  src/components/common/Footer.jsx
  src/styles/utils.jsx
Labels: 🎨 Styling

#57 Feat/issue-#55
  package-lock.json
  package.json
  src/components/common/MessageWriteButton.jsx
  src/components/template/AuthRedirectTemplate.jsx
  src/components/template/HomeTemplate.jsx
  src/components/template/SearchTemplate.jsx
  src/store/previousPageSlice.js
  src/store/store.js
Labels: ✨ Feature, 📬 API

#60 Feat/issue-#55
  src/components/common/MessageWriteButton.jsx
  src/components/template/AuthRedirectTemplate.jsx
  src/components/template/ChattingTemplate.jsx
  src/components/template/FriendTemplate.jsx
  src/components/template/HomeTemplate.jsx
  src/components/template/SearchTemplate.jsx
  src/store/currentPageSlice.js
  src/store/previousPageSlice.js
  src/store/store.js
Labels: 🔨 Refactor

#41 Feat/issue-#34
  package-lock.json
  package.json
  postcss.config.js
  src/App.css
  src/App.jsx
  src/assets/happynewhere_logo 1.svg
  src/components/common/Button/KakaoLoginBtn.jsx
  src/components/common/MessageWrite.jsx
  src/components/common/Profile.jsx
  src/components/organisms/UserInfo/IdInputBar.jsx
  src/components/organisms/UserInfo/IdInputBarPc.jsx
  src/components/organisms/UserInfo/IdInputContainer.jsx
  src/components/organisms/UserInfo/IdInputForm.jsx
  src/components/organisms/UserInfo/IdMobileStyle.jsx
  src/components/organisms/UserInfo/IdPcStyle.jsx
  src/components/organisms/UserInfo/IdSubmitButton.jsx
  src/components/organisms/UserInfo/StateInputBar.jsx
  src/components/template/AuthRedirectTemplate.jsx
  src/components/template/AuthTemplate.jsx
  src/components/template/HomeTemplate.jsx
  src/components/template/IdTemplate.jsx
  src/index.css
  src/pages/Id.jsx
  src/store/User-Slice.js
  src/store/User-action.js
  src/store/currentPageSlice.js
  src/store/store.js
  src/utils/URL.jsx
  tailwind.config.js
Labels: ✨ Feature, 🎨 Styling, ✅ Test, 📬 API

#70 Feat/issue-#49
  src/assets/DefaultProfileImg.png
  src/components/common/Footer.jsx
  src/components/common/Profile.jsx
  src/store/User-Slice.js
  src/store/User-action.js
Labels: ✨ Feature, 📬 API

#72 Feat/issue-#64
  src/components/common/Search/ProfileSearch.jsx
  src/components/organisms/Search/RecentSearch.jsx
  src/components/organisms/Search/ResultSearch.jsx
  src/components/template/SearchTemplate.jsx
  src/store/search-action.js
  src/store/searchSlice.js
  src/styles/Img.jsx
  src/styles/text.jsx
Labels: ✨ Feature, ✅ Test, 📬 API

#65 Feat/issue-#62
  package.json
  src/components/organisms/UserInfo/IdInputBar.jsx
  src/components/organisms/UserInfo/IdInputForm.jsx
  src/components/organisms/UserInfo/IdPcStyle.jsx
  src/components/organisms/UserInfo/IdSubmitButton.jsx
  src/components/organisms/UserInfo/LogoWrapper.jsx
  src/components/organisms/UserInfo/StateInputBar.jsx
  src/components/template/IdTemplate.jsx
  src/store/store.js
Labels: 👹 Bug, 🔨 Refactor, 🎨 Styling

#77 Feat/issue-#76
  src/App.jsx
  src/components/common/Footer.jsx
  src/pages/Root.jsx
Labels: 👹 Bug, 🔨 Refactor, ✅ Test

#79 Feat/issue-#75
  src/App.jsx
  src/components/common/Profile.jsx
  src/components/common/Search/SearchBar.jsx
  src/components/organisms/Search/ProfileSearch.jsx
  src/components/organisms/Search/ResultSearch.jsx
  src/components/organisms/Search/SearchBar.jsx
  src/components/template/FriendTemplate.jsx
  src/components/template/SearchTemplate.jsx
  src/store/searchingRouterSlice.js
  src/store/store.js
  src/styles/Img.jsx
Labels: ✨ Feature, 🔨 Refactor, ✅ Test

#81 Feat/issue-#80
  src/App.jsx
  src/components/common/Profile.jsx
  src/components/common/ProfileSearcing.jsx
  src/components/organisms/Message/TodayQuestionOrganism.jsx
  src/components/organisms/Search/ProfileSearch.jsx
  src/components/organisms/Search/RecentSearch.jsx
  src/components/organisms/Search/ResultSearch.jsx
  src/components/template/FriendTemplate.jsx
  src/store/search-action.js
  src/store/searchingRouterSlice.js
  src/store/store.js
  src/styles/profileStyle.jsx
Labels: ✨ Feature, ✅ Test, 📬 API

#83 Feat/issue-#82
  src/components/organisms/Search/ProfileSearch.jsx
  src/components/organisms/Search/ResultSearch.jsx
  src/components/organisms/UserInfo/IdInputBarPc.jsx
  src/components/organisms/UserInfo/IdInputContainer.jsx
  src/components/organisms/UserInfo/IdInputForm.jsx
  src/components/organisms/UserInfo/IdMobileStyle.jsx
  src/components/organisms/UserInfo/IdSubmitButton.jsx
  src/components/template/IdTemplate.jsx
  src/store/User-action.js
  src/styles/idStyle.jsx
Labels: ✨ Feature, 🎨 Styling, ✅ Test, 📬 API

#90 Feat/issue-#89
  src/components/common/MessageView.jsx
  src/components/common/MessageWrite.jsx
  src/components/template/FriendTemplate.jsx
  src/styles/utils.jsx
Labels: ✨ Feature, 🎨 Styling, ✅ Test, 📬 API

#92 Feat/issue-#33
  src/components/common/EditProfileTab.jsx
  src/components/common/ProfileSubmitButton.jsx
  src/components/template/EditProfileTemplate.jsx
Labels: ✨ Feature, 🎨 Styling

#94 Feat/issue #91
  src/components/common/Toast.jsx
  src/components/template/IdTemplate.jsx
Labels: ✨ Feature, ✅ Test, 📬 API

#96 [Refactor]: 호출 -> 알림 으로 변경
  src/components/common/Toast.jsx
  src/components/template/IdTemplate.jsx
Labels: 🔨 Refactor

#93 Feat/issue #43
  src/components/common/Profile.jsx
  src/components/template/FriendTemplate.jsx
  src/components/template/HomeTemplate.jsx
  src/components/template/IdTemplate.jsx
  src/components/template/SearchTemplate.jsx
  src/store/User-action.js
  src/styles/utils.jsx
Labels: 👹 Bug, 🔨 Refactor, 🎨 Styling

#109 Feat/issue #74
  src/assets/bell_green.svg
  src/assets/bell_pink.svg
  src/assets/bell_white.svg
  src/components/common/BellSVG.jsx
  src/components/common/Calendar.jsx
  src/components/common/MessageThumbnail.jsx
  src/components/common/MessageView.jsx
  src/components/organisms/Message/MessageList.jsx
  src/components/template/EditProfileTemplate.jsx
  src/components/template/HomeTemplate.jsx
  src/components/template/IdTemplate.jsx
  src/store/User-action.js
  src/store/calendar-slice.js
  src/store/store.js
Labels: ✨ Feature, ✅ Test, 📬 API

#114 Feat/issue-#88
  src/components/common/Toast.jsx
  src/components/organisms/Search/ProfileSearch.jsx
  src/components/template/FriendTemplate.jsx
  src/components/template/IdTemplate.jsx
  src/store/searchUserSlice.js
  src/store/store.js
Labels: ✨ Feature, ✅ Test

#102 Feat/issue #99.2
  src/components/common/Footer.jsx
  src/components/organisms/EditProfileOrganism.jsx
Labels: ✨ Feature

#115 Feat/issue #110
  src/components/common/MessageThumbnail.jsx
  src/components/organisms/Message/MessageList.jsx
  src/components/organisms/Message/MessageViewOrganism.jsx
  src/components/organisms/Message/TodayQuestionOrganism.jsx
  src/components/template/HomeTemplate.jsx
Labels: ✨ Feature, 🔨 Refactor, ✅ Test, 📬 API

#104 Feat/issue-#100
  src/components/common/Calendar.jsx
  src/components/common/EditProfileTab.jsx
  src/components/common/Profile.jsx
  src/components/organisms/EditProfile/ProfileHearderBar.jsx
  src/components/organisms/Home/ContentLayoutMobile.jsx
  src/components/template/EditProfileTemplate.jsx
  src/components/template/HomeTemplate.jsx
  src/components/template/SearchTemplate.jsx
  src/styles/profileStyle.jsx
  src/styles/utils.jsx
Labels: 👹 Bug, 🔨 Refactor, 🎨 Styling

#107 Feat/issue-#44
  src/assets/MessagePapers/Brown/Town.svg
  src/assets/MessagePapers/Green/Town.svg
  src/assets/MessagePapers/Navy/Town.svg
  src/assets/MessagePapers/Pink/Town.svg
  src/assets/MessagePapers/Red/Town.svg
  src/assets/MessagePapers/White/Town.svg
  src/assets/MessagePapers/Yellow/Town.svg
  src/components/common/AnonymousCheckbox.jsx
  src/components/common/MessagePaperThumbnail.jsx
  src/components/common/MessageSendButton.jsx
  src/components/common/MessageWrite.jsx
  src/components/organisms/Message/MessagePaperThumbnailOrganism.jsx
  src/styles/messageStyles.jsx
Labels: 📬 API

#118 Feat/issue #111
  src/components/organisms/Message/TodayQuestionOrganism.jsx
  src/components/template/HomeTemplate.jsx
Labels: 👹 Bug, ✨ Feature, 🔨 Refactor, ✅ Test, 📬 API

#120 Feat/issue #103
  src/components/common/GiftBox.css
  src/components/common/GiftBox.jsx
  src/components/organisms/Message/MessageList.jsx
  src/components/organisms/Message/TodayQuestionOrganism.jsx
  src/components/template/HomeTemplate.jsx
Labels: 👹 Bug, ✨ Feature, 🔨 Refactor, 🎨 Styling, ✅ Test, 📬 API

#125 [Style]: 글자크기 수정 / 40자 제한 확인
  src/components/common/Profile.jsx
  src/components/template/HomeTemplate.jsx
Labels: 🎨 Styling

#126 Feat & Deploy/issue-#117
  package-lock.json
  package.json
  src/components/common/Button/KakaoLoginBtn.jsx
  src/components/common/EditProfile/ProfileSubmitButton.jsx
  src/components/organisms/devWithComponent.txt
  src/components/template/AuthRedirectTemplate.jsx
  src/components/template/DevWithPages.txt
  src/components/template/HomeTemplate.jsx
  src/setupProxy.jsx
  src/store/User-action.js
  src/store/search-action.js
Labels: 🌏 Deploy, ✨ Feature, 🌇 Establish, 📬 API

#129 Chore/issue-#128
  src/App.jsx
  src/components/organisms/Search/ProfileSearch.jsx
  src/components/template/FriendTemplate.jsx
  src/components/template/HomeTemplate.jsx
Labels: ✨ Feature

#136 [Fix] 달력엑박오류 : import로 경로 수정
  src/components/common/BellSVG.jsx
Labels: 👹 Bug

#138 [HOTFIX] import 경로 수정 MessagePapersSRC
  src/utils/MessagePapersSRC.jsx
Labels: 👹 Bug

#146 dev
  src/components/common/Footer.jsx
  src/components/organisms/Search/ProfileSearch.jsx
  src/components/template/EditProfileTemplate.jsx
  src/components/template/FriendTemplate.jsx
  src/components/template/HomeTemplate.jsx
  src/components/template/IdTemplate.jsx
  src/components/template/SearchTemplate.jsx
Labels: 👹 Bug

#148 dev
  src/components/organisms/UserInfo/IdInputBar.jsx
  src/components/organisms/UserInfo/StateInputBar.jsx
  src/components/template/AuthTemplate.jsx
  src/components/template/IdTemplate.jsx
Labels: 🔨 Refactor, 🎨 Styling

#147 Feat/issue #145
  index.html
  src/App.jsx
  src/assets/Info.svg
  src/assets/info_gray.png
  src/assets/manual.svg
  src/components/common/Footer.jsx
  src/components/common/Header.jsx
  src/components/template/HomeTemplate.jsx
  src/components/template/InfoTemplate.jsx
  src/pages/Info.jsx
Labels: ✨ Feature, 🔨 Refactor, 🎨 Styling, ✅ Test

#150 [Style]: Footer 너무 작아서 수정
  src/components/common/Footer.jsx
Labels: 🎨 Styling

#151 main update
  index.html
  src/App.jsx
  src/assets/Info.svg
  src/assets/info_gray.png
  src/assets/manual.svg
  src/components/common/Footer.jsx
  src/components/common/Header.jsx
  src/components/template/HomeTemplate.jsx
  src/components/template/InfoTemplate.jsx
  src/pages/Info.jsx
Labels: 👹 Bug, 🔨 Refactor, 🎨 Styling

#153 Feat/issue #152
  src/components/common/GiftBox.css
Labels: 🎨 Styling

#158 Feat/issue-156
  src/components/common/Toast.jsx
  src/components/organisms/Search/ProfileSearch.jsx
  src/components/organisms/Search/RecentSearch.jsx
  src/components/template/SearchTemplate.jsx
Labels: 👹 Bug, ✨ Feature, 🔨 Refactor, ✅ Test

#154 main update 서버 업데이트 예정
  src/components/common/GiftBox.css
  src/components/common/Toast.jsx
  src/components/organisms/Search/ProfileSearch.jsx
  src/components/organisms/Search/RecentSearch.jsx
  src/components/template/SearchTemplate.jsx
Labels: 🎨 Styling

#160 Refactor/issue-#159
  src/components/organisms/Search/ProfileSearch.jsx
  src/components/organisms/Search/ResultSearch.jsx
  src/components/template/SearchTemplate.jsx
Labels: ✨ Feature, 🔨 Refactor, ✅ Test

#161 Dev
  src/components/organisms/Search/ProfileSearch.jsx
  src/components/organisms/Search/ResultSearch.jsx
  src/components/template/SearchTemplate.jsx
Labels: ✨ Feature, 🔨 Refactor

#162 Feat/issue-#113
  src/components/common/Footer.jsx
  src/components/common/MessageWrite.jsx
  src/components/organisms/EditProfile/EditProfileTab.jsx
  src/store/UserInfoInputSlice.js
Labels: ✨ Feature

#164 Feat/issue-#163
  src/components/common/EditProfile/EditUserInfo.jsx
  src/components/common/EditProfile/ProfileSubmitButton.jsx
  src/components/organisms/EditProfile/EditProfileTab.jsx
Labels: ✨ Feature, 📬 API

#165 dev
  src/components/common/EditProfile/EditUserInfo.jsx
  src/components/common/EditProfile/ProfileSubmitButton.jsx
  src/components/common/Footer.jsx
  src/components/common/MessageWrite.jsx
  src/components/organisms/EditProfile/EditProfileTab.jsx
  src/store/UserInfoInputSlice.js
Labels: ✨ Feature, 📬 API
