Repository Happy-New-Here/HappyNewHere_FE, pull requests merged in 2024-01, with the labels that each got.

#175 Feat/issue #174
  src/components/common/Header.jsx
  src/components/common/MessageThumbnail.jsx
  src/components/common/MessageView.jsx
  src/components/organisms/Message/MessageList.jsx
  src/components/organisms/Message/MessageViewOrganism.jsx
  src/components/organisms/Message/TodayQuestionOrganism.jsx
  src/components/template/HomeTemplate.jsx
Labels: 👹 Bug

#177 [Feat]: 메세지 삭제 기능 추가
  src/components/common/MessageView.jsx
  src/components/organisms/Message/MessageList.jsx
  src/store/isMessageViewVisibleSlice.js
  src/store/store.js
Labels: ✨ Feature

#178 Fix/issue-#173
  src/components/common/MessageThumbnail.jsx
  src/components/common/MessageView.jsx
  src/components/organisms/Message/MessageViewOrganism.jsx
  src/components/organisms/Message/TodayQuestionOrganism.jsx
  src/styles/messageStyles.jsx
  src/utils/MessagePapersSRC.jsx
Labels: 👹 Bug, 🎨 Styling
